export default {
    "About":                                                                        "About",
    "All fields are required and must be valid":                                    "All fields are required and must be valid",
    "Credits":                                                                      "Credits",
    "Details":                                                                      "Details",
    "Donate":                                                                       "Donate",
    "Error submitting suggested name":                                              "Error submitting suggested name",
    "Meaning/History of Name":                                                      "Meaning/History of Name",
    "Names":                                                                        "Names",
    "Names database failed to initialized, You can try again in the settings menu": "Names database failed to initialized, You can try again in the settings menu",
    "New Name":                                                                     "New Name",
    "Notification Email":                                                           "Notification Email",
    "Select":                                                                       "Select",
    "Settings":                                                                     "Settings",
    "Suggest":                                                                      "Suggest",
    "Suggest a Name":                                                               "Suggest a Name",
    "Suggested name submitted successfully":                                        "Suggested name submitted successfully",
    "There are no names submitted yet":                                             "There are no names submitted yet",
    "Updating Name Database":                                                       "Updating Name Database",
    "Updating of Name Database Fail":                                               "Updating of Name Database Fail",
    "Updating of Name Database Successful":                                         "Updating of Name Database Successful",
    "Volunteer":                                                                    "Volunteer",
    "welcome":                                                                      "welcome",
    "Where did you hear or were given the name:":                                   "Where did you hear or were given the name:",
    "Your internet is not reachable. Connect to a working internet to continue":    "Your internet is not reachable. Connect to a working internet to continue",
    "Your search does not match any names":                                         "Your search does not match any names",
};
